// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthInfo struct {
	LoginCount     int        `json:"loginCount"`
	LastLoginAt    *string    `json:"lastLoginAt,omitempty"`
	ActiveSessions []*Session `json:"activeSessions"`
}

type AuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
	ExpiresAt    string `json:"expiresAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Session struct {
	ID           string  `json:"id"`
	DeviceType   *string `json:"deviceType,omitempty"`
	IPAddress    *string `json:"ipAddress,omitempty"`
	LastActiveAt string  `json:"lastActiveAt"`
	IsActive     bool    `json:"isActive"`
}

type Subscription struct {
}

type User struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
	LastLoginAt *string   `json:"lastLoginAt,omitempty"`
	AuthInfo    *AuthInfo `json:"authInfo,omitempty"`
}
