// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthInfo struct {
	LoginCount     int        `json:"loginCount"`
	LastLoginAt    *string    `json:"lastLoginAt,omitempty"`
	ActiveSessions []*Session `json:"activeSessions"`
}

type AuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
	ExpiresAt    string `json:"expiresAt"`
}

type BatchUpdateInput struct {
	TodoIds []string         `json:"todoIds"`
	Updates *UpdateTodoInput `json:"updates"`
}

type CreateTodoInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Session struct {
	ID           string  `json:"id"`
	DeviceType   *string `json:"deviceType,omitempty"`
	IPAddress    *string `json:"ipAddress,omitempty"`
	LastActiveAt string  `json:"lastActiveAt"`
	IsActive     bool    `json:"isActive"`
}

type Subscription struct {
}

type Todo struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Completed   bool    `json:"completed"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	User        *User   `json:"user"`
}

type TodoFilter struct {
	Completed *bool   `json:"completed,omitempty"`
	Search    *string `json:"search,omitempty"`
	Limit     *int    `json:"limit,omitempty"`
	Offset    *int    `json:"offset,omitempty"`
}

type TodoListResponse struct {
	Todos   []*Todo `json:"todos"`
	Total   int     `json:"total"`
	Limit   int     `json:"limit"`
	Offset  int     `json:"offset"`
	HasMore bool    `json:"hasMore"`
}

type TodoStats struct {
	Total     int `json:"total"`
	Completed int `json:"completed"`
	Pending   int `json:"pending"`
}

type UpdateTodoInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
}

type User struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
	LastLoginAt *string   `json:"lastLoginAt,omitempty"`
	AuthInfo    *AuthInfo `json:"authInfo,omitempty"`
}
