package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strconv"

	"github.com/jayk0001/my-go-next-todo/internal/graphql/generated"
	"github.com/jayk0001/my-go-next-todo/internal/graphql/model"
	"github.com/jayk0001/my-go-next-todo/internal/middleware"
)

func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	// Use the auth service to register a new user
	authResult, err := r.AuthService.Register(ctx, input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	// Convert auth result to GraphQL model
	return authResult.ToGraphQLAuthPayload(), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// Use the auth service to authenticate user
	authResult, err := r.AuthService.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	// Convert auth result to GraphQL model
	return authResult.ToGraphQLAuthPayload(), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthPayload, error) {
	// Use the auth service to refresh token
	authResult, err := r.AuthService.RefreshToken(ctx, token)
	if err != nil {
		return nil, fmt.Errorf("failed to refresh token: %w", err)
	}

	// Convert auth result to GraphQL model
	return authResult.ToGraphQLAuthPayload(), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// For now, logous is just a simple success response
	// TODO: Implement actual logout logic (token blacklist, session invalidation)
	return true, nil
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*model.User, error) {
	user, ok := middleware.GetUserFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("user not authenticated")
	}
	return user.ToGraphQLUser(), nil
}

// UserProfile is the resolver for the userProfile field.
func (r *queryResolver) UserProfile(ctx context.Context, id string) (*model.User, error) {
	// Convert string ID to int
	userID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid User ID: %w", err)
	}

	user, err := r.AuthService.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user profile: %w", err)
	}

	// Convert auth user to GraphQL model
	return user.ToGraphQLUser(), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// AuthStatusChanged is the resolver for the authStatusChanged field.
func (r *subscriptionResolver) AuthStatusChanged(ctx context.Context) (<-chan *model.User, error) {
	// Create a channel for user updates
	userChan := make(chan *model.User, 1)

	// TODO: implement real-time auth status subscription
	// For now, return an empty channel that closes when context is done
	go func() {
		defer close(userChan)
		<-ctx.Done()
	}()

	return userChan, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
